// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1dIV7oBVBwB_2kGbFs9T--QqpgP8rZ5g',
    appId: '1:253389045243:web:6eb24494986befdaf3df5e',
    messagingSenderId: '253389045243',
    projectId: 'login-page-87853',
    authDomain: 'login-page-87853.firebaseapp.com',
    storageBucket: 'login-page-87853.appspot.com',
    measurementId: 'G-KZ8NXXJ5YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxBQpz4abpeepYp5dCJBC7U6fURfBcRA',
    appId: '1:253389045243:android:9ad2db2515a37e8bf3df5e',
    messagingSenderId: '253389045243',
    projectId: 'login-page-87853',
    storageBucket: 'login-page-87853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnN6aLKgxBeOcJ_XQcmExk7NqMXarU_sM',
    appId: '1:253389045243:ios:3a677846bf6e5098f3df5e',
    messagingSenderId: '253389045243',
    projectId: 'login-page-87853',
    storageBucket: 'login-page-87853.appspot.com',
    iosBundleId: 'com.example.netflixLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnN6aLKgxBeOcJ_XQcmExk7NqMXarU_sM',
    appId: '1:253389045243:ios:ae1e9797232a2034f3df5e',
    messagingSenderId: '253389045243',
    projectId: 'login-page-87853',
    storageBucket: 'login-page-87853.appspot.com',
    iosBundleId: 'com.example.netflixLogin.RunnerTests',
  );
}
